In [1]:
import cv2
import numpy as np
import os

In [2]:
webcam = cv2.VideoCapture(0)
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

count = 0
face_data = []
dataset_path = './knn_openCV/'
offset = 10

file_name = input("Enter the name of the person :  ")
while True:
    ret,frame = webcam.read()
    
    if(ret == False):
        continue
        
    gray_frame = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)    
    faces = face_cascade.detectMultiScale(frame, 1.3, 5)
    #print('before sorting', faces)
    faces = sorted(faces, key=lambda f:f[2]*f[3])
    #print('after sorting', faces)
    
    # pick the last face (largest)
    for face in faces[-1:]:
        x, y, w, h =  face 
        cv2.rectangle(frame, (x,y), (x+w, y+h), (255,0,0), 2)
    
    # extract only face in different window 
    face_section = frame[y-offset:y+h+offset, x-offset:x+w+offset]
    face_section = cv2.resize(face_section,(100,100))
    print('face section', face_section)
    count += 1
    print('count', count)
    if(count % 10 == 0):
        face_data.append(face_section)
        print('face data length', len(face_data))      
    cv2.imshow("FACE CROP",face_section) 
    cv2.imshow("WEBCAM",frame)
        
    if cv2.waitKey(1) & 0xFF == ord('q'):
            break
webcam.release()
cv2.destroyAllWindows()        
# convert our face list array into a numpy array
face_data = np.array(face_data)
#print("face shape ", face_data.shape)
#print("face shape[0] ", face_data.shape[0])
face_data = face_data.reshape((face_data.shape[0],-1)) 
#print("reshape ", face_data.shape)

#save this data into numpy array file & text file 
np.save(dataset_path + file_name + '.npy', face_data)
print("data successfully saved at " + dataset_path + file_name + '.npy')

Enter the name of the person :  hy_mask
face section [[[180 190 187]
  [181 192 186]
  [182 193 187]
  ...
  [175 181 175]
  [173 180 173]
  [170 178 171]]

 [[181 190 187]
  [182 190 187]
  [183 191 186]
  ...
  [173 182 174]
  [173 181 174]
  [170 179 172]]

 [[184 193 187]
  [182 190 185]
  [185 193 187]
  ...
  [173 181 176]
  [173 181 176]
  [172 179 174]]

 ...

 [[ 28  44  66]
  [ 29  46  71]
  [ 32  49  77]
  ...
  [ 22  32  47]
  [ 24  37  52]
  [ 19  33  48]]

 [[ 27  44  64]
  [ 29  46  68]
  [ 34  50  75]
  ...
  [ 25  33  49]
  [ 29  40  55]
  [ 26  39  54]]

 [[ 31  44  66]
  [ 29  45  67]
  [ 36  53  74]
  ...
  [ 22  28  46]
  [ 28  38  56]
  [ 26  38  55]]]
count 1
face section [[[183 192 190]
  [179 189 187]
  [176 187 185]
  ...
  [174 180 175]
  [171 179 173]
  [170 178 174]]

 [[182 192 191]
  [180 192 191]
  [178 190 189]
  ...
  [175 181 176]
  [172 180 175]
  [171 179 173]]

 [[183 192 189]
  [179 191 188]
  [177 189 186]
  ...
  [173 181 176]
  [173 180 177]
  

face section [[[184 196 193]
  [184 195 191]
  [185 195 192]
  ...
  [179 187 182]
  [178 186 180]
  [178 186 180]]

 [[186 197 194]
  [186 196 192]
  [184 193 190]
  ...
  [179 187 182]
  [179 186 182]
  [179 186 182]]

 [[187 197 194]
  [185 195 191]
  [187 194 191]
  ...
  [181 187 182]
  [181 187 182]
  [180 185 180]]

 ...

 [[ 45  52  70]
  [ 38  47  67]
  [ 40  53  77]
  ...
  [ 16  26  43]
  [ 16  25  45]
  [ 23  31  51]]

 [[ 45  55  72]
  [ 37  48  69]
  [ 39  55  78]
  ...
  [ 20  27  44]
  [ 21  28  46]
  [ 22  31  51]]

 [[ 44  58  72]
  [ 38  51  70]
  [ 35  52  75]
  ...
  [ 21  29  44]
  [ 23  31  48]
  [ 22  31  48]]]
count 14
face section [[[185 194 193]
  [186 196 193]
  [186 197 193]
  ...
  [179 186 182]
  [178 185 181]
  [178 186 182]]

 [[187 194 193]
  [188 195 194]
  [183 194 193]
  ...
  [180 186 183]
  [178 185 183]
  [178 185 182]]

 [[188 196 193]
  [187 195 192]
  [183 194 193]
  ...
  [181 187 182]
  [180 186 182]
  [178 185 182]]

 ...

 [[ 55  59  79]
 

  [ 32  39  61]]]
count 29
face section [[[186 195 193]
  [186 196 193]
  [186 196 193]
  ...
  [179 187 182]
  [178 186 180]
  [179 187 182]]

 [[185 195 191]
  [185 195 191]
  [185 195 191]
  ...
  [179 186 183]
  [179 186 182]
  [179 186 183]]

 [[186 196 193]
  [185 195 191]
  [185 195 191]
  ...
  [178 185 182]
  [178 185 182]
  [178 185 182]]

 ...

 [[ 56  61  82]
  [ 44  50  74]
  [ 41  54  78]
  ...
  [ 23  28  46]
  [ 29  36  55]
  [ 29  38  58]]

 [[ 47  55  75]
  [ 40  49  72]
  [ 43  55  79]
  ...
  [ 24  30  48]
  [ 29  36  55]
  [ 29  39  61]]

 [[ 50  58  77]
  [ 42  50  73]
  [ 39  51  77]
  ...
  [ 23  31  46]
  [ 27  37  54]
  [ 29  40  58]]]
count 30
face data length 3
face section [[[188 196 193]
  [186 196 193]
  [184 195 193]
  ...
  [177 185 183]
  [179 186 182]
  [181 187 182]]

 [[188 196 193]
  [185 196 193]
  [183 194 193]
  ...
  [177 186 183]
  [179 187 182]
  [181 187 180]]

 [[188 196 193]
  [185 196 193]
  [184 195 194]
  ...
  [178 186 180]
  [177 185 

face section [[[183 194 193]
  [186 195 194]
  [187 195 193]
  ...
  [176 185 183]
  [179 186 182]
  [179 187 182]]

 [[184 195 194]
  [184 195 194]
  [186 195 194]
  ...
  [175 186 180]
  [179 187 182]
  [179 187 182]]

 [[187 196 196]
  [186 195 194]
  [185 194 193]
  ...
  [178 185 182]
  [181 186 183]
  [180 185 182]]

 ...

 [[ 57  66  84]
  [ 40  49  68]
  [ 42  53  75]
  ...
  [ 23  28  46]
  [ 29  36  54]
  [ 32  40  57]]

 [[ 54  64  83]
  [ 40  49  68]
  [ 42  52  74]
  ...
  [ 22  29  47]
  [ 29  36  54]
  [ 28  38  55]]

 [[ 52  63  82]
  [ 42  52  72]
  [ 43  53  72]
  ...
  [ 23  30  48]
  [ 28  35  54]
  [ 32  41  60]]]
count 44
face section [[[186 196 193]
  [184 195 191]
  [185 196 193]
  ...
  [178 185 182]
  [179 186 183]
  [179 186 183]]

 [[185 195 191]
  [185 195 191]
  [185 195 191]
  ...
  [178 185 183]
  [178 185 184]
  [178 185 184]]

 [[185 195 190]
  [185 195 190]
  [186 196 191]
  ...
  [179 186 183]
  [178 185 182]
  [178 185 182]]

 ...

 [[ 44  47  70]
 

face section [[[185 195 191]
  [184 193 190]
  [186 196 193]
  ...
  [181 186 183]
  [181 186 183]
  [181 186 184]]

 [[186 196 193]
  [185 195 191]
  [186 196 193]
  ...
  [178 185 182]
  [179 186 183]
  [180 187 183]]

 [[187 196 191]
  [186 196 193]
  [185 197 194]
  ...
  [179 187 182]
  [178 185 182]
  [179 186 183]]

 ...

 [[ 41  54  76]
  [ 39  52  75]
  [ 36  53  77]
  ...
  [ 28  37  57]
  [ 31  40  59]
  [ 26  33  53]]

 [[ 39  56  77]
  [ 36  49  71]
  [ 38  53  77]
  ...
  [ 27  36  56]
  [ 33  42  62]
  [ 25  35  55]]

 [[ 38  53  77]
  [ 35  47  73]
  [ 44  60  81]
  ...
  [ 26  36  57]
  [ 31  43  63]
  [ 27  38  58]]]
count 59
face section [[[185 195 191]
  [185 195 191]
  [186 196 193]
  ...
  [180 185 182]
  [181 187 182]
  [181 187 182]]

 [[185 194 191]
  [185 195 191]
  [187 197 194]
  ...
  [179 184 181]
  [181 187 182]
  [181 187 182]]

 [[187 194 191]
  [185 195 191]
  [187 197 194]
  ...
  [179 184 181]
  [182 185 180]
  [184 187 183]]

 ...

 [[ 44  53  72]
 

face section [[[185 195 192]
  [186 196 193]
  [187 197 193]
  ...
  [177 186 183]
  [176 186 182]
  [175 186 181]]

 [[185 195 191]
  [186 196 193]
  [187 197 194]
  ...
  [179 187 182]
  [179 187 182]
  [178 186 180]]

 [[188 196 193]
  [187 194 191]
  [184 194 190]
  ...
  [180 187 183]
  [180 188 183]
  [178 186 180]]

 ...

 [[ 55  67  87]
  [ 42  54  74]
  [ 40  49  69]
  ...
  [ 33  42  61]
  [ 28  37  57]
  [ 26  33  52]]

 [[ 51  65  84]
  [ 40  55  73]
  [ 41  51  68]
  ...
  [ 35  42  62]
  [ 32  39  59]
  [ 27  34  53]]

 [[ 48  63  83]
  [ 39  54  73]
  [ 38  49  69]
  ...
  [ 36  43  63]
  [ 34  42  62]
  [ 29  37  56]]]
count 77
face section [[[185 194 194]
  [185 196 196]
  [185 197 194]
  ...
  [179 187 182]
  [181 187 182]
  [180 185 179]]

 [[188 196 193]
  [187 197 194]
  [185 197 194]
  ...
  [178 185 182]
  [182 187 183]
  [181 186 182]]

 [[188 196 193]
  [188 195 194]
  [186 195 194]
  ...
  [179 186 183]
  [180 187 184]
  [179 187 183]]

 ...

 [[ 42  53  75]
 

face section [[[ 88  85  67]
  [ 82  76  63]
  [175 181 185]
  ...
  [178 185 182]
  [176 184 182]
  [172 181 180]]

 [[ 89  86  70]
  [ 84  79  68]
  [176 186 190]
  ...
  [179 186 183]
  [175 185 182]
  [174 184 181]]

 [[ 87  86  70]
  [ 83  80  69]
  [176 187 192]
  ...
  [179 186 183]
  [177 186 184]
  [174 184 180]]

 ...

 [[ 64  73  82]
  [ 52  61  71]
  [ 46  55  70]
  ...
  [ 32  40  52]
  [ 29  36  48]
  [ 31  39  51]]

 [[ 59  68  78]
  [ 49  57  70]
  [ 50  58  73]
  ...
  [ 38  50  60]
  [ 32  43  53]
  [ 29  41  51]]

 [[ 57  66  80]
  [ 45  53  69]
  [ 48  57  73]
  ...
  [ 36  49  59]
  [ 29  42  53]
  [ 27  39  52]]]
count 95
face section [[[ 85  83  65]
  [118 118 114]
  [181 192 197]
  ...
  [180 186 183]
  [179 185 181]
  [177 184 181]]

 [[ 87  83  65]
  [128 127 125]
  [178 191 196]
  ...
  [179 186 183]
  [178 185 182]
  [177 184 182]]

 [[ 89  84  65]
  [137 137 133]
  [177 190 194]
  ...
  [180 187 184]
  [178 185 182]
  [179 186 183]]

 ...

 [[ 50  62  79]
 

face section [[[ 77  76  67]
  [ 73  70  63]
  [145 146 157]
  ...
  [158 171 175]
  [158 171 175]
  [157 170 174]]

 [[ 77  76  67]
  [ 74  70  63]
  [144 145 154]
  ...
  [160 172 173]
  [159 171 173]
  [157 171 172]]

 [[ 77  76  67]
  [ 72  67  58]
  [153 153 158]
  ...
  [158 171 175]
  [158 173 176]
  [155 170 174]]

 ...

 [[ 54  72  99]
  [ 46  66  88]
  [ 41  57  81]
  ...
  [ 23  38  54]
  [ 10  20  35]
  [  9  18  33]]

 [[ 48  70  97]
  [ 44  66  89]
  [ 37  53  76]
  ...
  [ 33  44  62]
  [ 21  32  49]
  [  9  19  36]]

 [[ 46  69  97]
  [ 44  64  87]
  [ 36  52  76]
  ...
  [ 34  43  63]
  [ 35  45  62]
  [ 23  32  49]]]
count 113
face section [[[ 75  70  62]
  [ 80  78  67]
  [ 80  77  64]
  ...
  [156 170 174]
  [157 170 174]
  [158 171 175]]

 [[ 78  72  64]
  [ 79  77  66]
  [ 79  76  63]
  ...
  [158 172 178]
  [156 171 175]
  [156 171 175]]

 [[ 75  70  63]
  [ 79  76  68]
  [ 79  75  65]
  ...
  [156 170 176]
  [157 170 175]
  [157 170 174]]

 ...

 [[ 58  77 102]


face section [[[ 92  91  85]
  [ 94  94  84]
  [ 91  87  72]
  ...
  [176 191 194]
  [173 190 193]
  [173 190 193]]

 [[ 93  92  82]
  [ 94  94  81]
  [ 90  87  73]
  ...
  [176 191 194]
  [176 191 195]
  [177 192 193]]

 [[ 94  91  82]
  [ 95  93  83]
  [ 90  85  74]
  ...
  [178 191 194]
  [179 193 196]
  [175 190 193]]

 ...

 [[ 79  98 118]
  [ 74  97 120]
  [ 70  93 117]
  ...
  [ 49  61  80]
  [ 28  37  65]
  [ 21  25  49]]

 [[ 69  94 127]
  [ 68  94 122]
  [ 66  90 117]
  ...
  [ 49  63  82]
  [ 43  62  85]
  [ 19  29  55]]

 [[ 69  93 129]
  [ 65  89 120]
  [ 63  87 114]
  ...
  [ 49  61  78]
  [ 48  64  83]
  [ 45  59  81]]]
count 128
face section [[[ 91  91  82]
  [ 92  93  83]
  [ 88  86  74]
  ...
  [175 191 195]
  [176 191 194]
  [176 191 194]]

 [[ 91  91  81]
  [ 92  92  81]
  [ 87  83  72]
  ...
  [176 193 197]
  [174 192 194]
  [173 191 193]]

 [[ 92  92  81]
  [ 93  92  82]
  [ 89  85  74]
  ...
  [177 192 197]
  [176 191 194]
  [174 189 192]]

 ...

 [[ 74  87 104]


face section [[[ 97  95  84]
  [ 98  92  79]
  [141 140 139]
  ...
  [178 194 197]
  [179 193 199]
  [176 191 196]]

 [[101  97  84]
  [101  93  78]
  [140 142 141]
  ...
  [178 193 198]
  [177 194 197]
  [176 193 196]]

 [[100  97  82]
  [ 99  91  74]
  [147 150 149]
  ...
  [178 193 198]
  [177 192 196]
  [176 193 196]]

 ...

 [[ 78 101 134]
  [ 78 100 132]
  [ 75  97 132]
  ...
  [ 51  67  88]
  [ 49  64  85]
  [ 58  69  92]]

 [[ 66  92 128]
  [ 70  93 130]
  [ 70  92 129]
  ...
  [ 48  65  89]
  [ 45  62  86]
  [ 49  60  84]]

 [[ 62  84 121]
  [ 63  84 121]
  [ 61  83 122]
  ...
  [ 47  62  86]
  [ 47  65  88]
  [ 46  61  85]]]
count 143
face section [[[198 209 217]
  [195 209 211]
  [200 212 211]
  ...
  [177 193 196]
  [178 194 197]
  [178 194 197]]

 [[194 207 219]
  [195 210 212]
  [198 211 212]
  ...
  [179 192 198]
  [180 192 196]
  [182 193 197]]

 [[197 209 222]
  [194 210 212]
  [196 210 211]
  ...
  [181 193 197]
  [181 194 197]
  [182 195 198]]

 ...

 [[ 80 103 134]


face section [[[197 210 213]
  [196 209 212]
  [197 210 213]
  ...
  [158 185 205]
  [ 57  73  96]
  [ 84  83  79]]

 [[198 211 214]
  [197 210 213]
  [198 211 214]
  ...
  [159 190 207]
  [ 59  77  98]
  [ 83  83  81]]

 [[198 211 212]
  [198 211 213]
  [198 211 214]
  ...
  [157 187 203]
  [ 57  78  96]
  [ 85  81  83]]

 ...

 [[ 65  87 112]
  [ 58  75 101]
  [ 60  73  97]
  ...
  [ 34  45  65]
  [ 19  28  46]
  [ 23  25  42]]

 [[ 64  83 109]
  [ 58  74 100]
  [ 58  69  95]
  ...
  [ 41  51  73]
  [ 27  36  59]
  [ 25  29  48]]

 [[ 66  82 106]
  [ 58  73  96]
  [ 54  67  93]
  ...
  [ 48  61  83]
  [ 32  45  69]
  [ 23  29  53]]]
count 160
face data length 16
face section [[[198 211 212]
  [196 211 214]
  [197 212 215]
  ...
  [162 189 202]
  [ 60  76  92]
  [ 87  82  81]]

 [[195 210 213]
  [195 210 213]
  [196 211 214]
  ...
  [158 188 204]
  [ 59  79  98]
  [ 86  83  82]]

 [[196 210 216]
  [196 211 215]
  [197 212 215]
  ...
  [161 190 205]
  [ 62  86 104]
  [ 84  81  80]]

 .

face section [[[102  98  85]
  [ 93  88  80]
  [204 214 223]
  ...
  [185 198 201]
  [180 193 197]
  [182 193 197]]

 [[102  98  85]
  [ 90  86  79]
  [207 218 227]
  ...
  [186 197 199]
  [182 194 197]
  [181 193 197]]

 [[101  97  84]
  [ 87  85  78]
  [206 222 229]
  ...
  [184 197 199]
  [182 195 198]
  [182 194 198]]

 ...

 [[162 161 146]
  [173 170 153]
  [174 170 151]
  ...
  [ 41  54  76]
  [ 38  47  71]
  [ 55  65  89]]

 [[175 178 162]
  [182 181 165]
  [192 189 173]
  ...
  [ 41  52  74]
  [ 36  45  68]
  [ 53  63  89]]

 [[104  97  88]
  [104  98  87]
  [103  98  86]
  ...
  [ 38  53  72]
  [ 39  48  66]
  [ 54  65  85]]]
count 176
face section [[[102  97  86]
  [ 90  85  77]
  [206 214 225]
  ...
  [184 197 200]
  [180 193 196]
  [181 193 199]]

 [[102  97  86]
  [ 89  84  80]
  [205 216 228]
  ...
  [184 197 199]
  [182 195 197]
  [179 192 196]]

 [[103  99  88]
  [ 93  87  82]
  [205 219 225]
  ...
  [184 198 197]
  [182 195 197]
  [181 195 198]]

 ...

 [[169 167 150]


face section [[[197 209 212]
  [198 210 213]
  [199 210 211]
  ...
  [178 193 198]
  [177 193 198]
  [176 190 196]]

 [[194 209 210]
  [193 208 210]
  [198 211 214]
  ...
  [179 194 197]
  [178 193 197]
  [181 193 199]]

 [[196 209 210]
  [195 207 209]
  [197 210 211]
  ...
  [178 194 197]
  [177 193 196]
  [179 192 197]]

 ...

 [[ 61  76 100]
  [ 61  71  95]
  [ 62  74 100]
  ...
  [ 17  20  35]
  [ 21  26  42]
  [ 27  34  51]]

 [[ 64  77 101]
  [ 61  70  94]
  [ 63  72  97]
  ...
  [ 17  21  32]
  [ 20  20  34]
  [ 27  29  45]]

 [[ 64  78 104]
  [ 59  70  94]
  [ 63  74  98]
  ...
  [ 21  28  42]
  [ 14  18  32]
  [ 19  20  36]]]
count 194
face section [[[202 214 215]
  [203 214 216]
  [204 215 216]
  ...
  [179 194 197]
  [180 195 198]
  [169 189 198]]

 [[201 215 216]
  [202 215 216]
  [202 215 216]
  ...
  [181 193 197]
  [181 193 197]
  [167 190 196]]

 [[203 215 214]
  [205 216 215]
  [205 216 215]
  ...
  [179 194 197]
  [179 195 198]
  [167 191 197]]

 ...

 [[ 45  56  85]


face section [[[203 215 212]
  [205 217 214]
  [206 218 215]
  ...
  [112 140 158]
  [ 76  77  80]
  [ 88  85  76]]

 [[203 216 214]
  [206 218 215]
  [208 218 215]
  ...
  [122 147 166]
  [ 78  79  84]
  [ 86  83  76]]

 [[207 216 216]
  [208 218 216]
  [208 218 215]
  ...
  [129 152 172]
  [ 75  74  85]
  [ 87  83  79]]

 ...

 [[ 57  76 108]
  [ 53  70 103]
  [ 60  77 108]
  ...
  [166 163 166]
  [187 190 186]
  [190 195 187]]

 [[ 55  76 105]
  [ 57  75 105]
  [ 63  81 111]
  ...
  [145 139 145]
  [176 176 174]
  [187 191 186]]

 [[ 57  76 103]
  [ 59  77 104]
  [ 60  77 105]
  ...
  [103  97 104]
  [178 177 174]
  [184 184 182]]]
count 211
face section [[[204 215 215]
  [206 218 217]
  [208 217 217]
  ...
  [112 138 158]
  [ 76  77  77]
  [ 85  84  74]]

 [[206 216 215]
  [208 217 217]
  [207 217 214]
  ...
  [123 149 168]
  [ 71  75  79]
  [ 85  84  77]]

 [[207 217 215]
  [208 218 215]
  [209 219 216]
  ...
  [131 158 174]
  [ 73  74  79]
  [ 86  82  78]]

 ...

 [[ 56  75 105]


face section [[[198 211 213]
  [200 211 212]
  [200 211 212]
  ...
  [158 162 150]
  [180 186 181]
  [182 190 187]]

 [[201 211 213]
  [201 212 213]
  [200 211 212]
  ...
  [158 162 149]
  [182 186 181]
  [183 191 186]]

 [[199 212 211]
  [201 213 212]
  [201 213 212]
  ...
  [156 162 149]
  [180 186 179]
  [183 191 186]]

 ...

 [[ 55  72  98]
  [ 52  66  93]
  [ 48  59  86]
  ...
  [ 16  24  39]
  [ 22  29  48]
  [ 29  32  54]]

 [[ 52  71  97]
  [ 49  65  91]
  [ 41  55  81]
  ...
  [ 10  15  31]
  [ 21  26  44]
  [ 24  28  48]]

 [[ 54  73  99]
  [ 50  66  92]
  [ 41  52  82]
  ...
  [  9  10  25]
  [ 15  17  37]
  [ 23  27  47]]]
count 229
face section [[[194 209 212]
  [197 209 210]
  [199 210 211]
  ...
  [181 190 187]
  [182 192 191]
  [181 191 190]]

 [[196 209 212]
  [199 210 211]
  [199 210 211]
  ...
  [180 189 187]
  [180 190 188]
  [181 191 189]]

 [[195 207 211]
  [197 209 210]
  [199 210 211]
  ...
  [176 188 184]
  [177 189 186]
  [180 189 189]]

 ...

 [[ 54  76 102]


face section [[[194 205 208]
  [193 204 206]
  [191 204 207]
  ...
  [174 189 191]
  [173 188 191]
  [175 190 193]]

 [[193 206 209]
  [194 206 207]
  [193 205 209]
  ...
  [175 190 194]
  [173 187 191]
  [175 189 193]]

 [[195 209 208]
  [193 207 207]
  [192 205 208]
  ...
  [174 188 194]
  [174 190 195]
  [174 189 194]]

 ...

 [[113 115 109]
  [ 86  92 101]
  [ 70  78  99]
  ...
  [ 36  42  57]
  [ 35  36  50]
  [ 49  54  66]]

 [[108 112 110]
  [ 97 106 110]
  [ 87  98 111]
  ...
  [ 37  46  69]
  [ 30  30  49]
  [ 47  48  62]]

 [[109 121 121]
  [ 96 110 116]
  [ 88 106 118]
  ...
  [ 45  57  84]
  [ 26  27  53]
  [ 36  34  53]]]
count 246
face section [[[194 207 208]
  [192 205 207]
  [192 205 207]
  ...
  [180 193 194]
  [180 193 194]
  [177 191 193]]

 [[195 209 207]
  [193 207 208]
  [192 206 207]
  ...
  [179 194 195]
  [179 193 194]
  [178 191 193]]

 [[195 208 208]
  [195 208 209]
  [195 208 210]
  ...
  [179 194 195]
  [177 193 194]
  [177 193 196]]

 ...

 [[ 72  81 101]


In [2]:
########## KNN CODE ############
def distance(v1, v2):
    # Eucledian 
    return np.sqrt(((v1-v2)**2).sum())

def knn(train, test, k=5):
    dist = []
    for i in range(train.shape[0]):
        # Get the vector and label
        ix = train[i, :-1]
        iy = train[i, -1]
        # Compute the distance from test point
        d = distance(test, ix)
        #print('eucledian dist ', d)
        dist.append([d, iy])
        #print('dist list ', dist)
    # Sort based on distance and get top k
    dk = sorted(dist, key=lambda x: x[0])[:k]
    #print('dk', dk)
    # Retrieve only the labels
    labels = np.array(dk)[:, -1]
    #print('labels', labels)
    # Get frequencies of each label
    output = np.unique(labels, return_counts=True)
    #print('output', output)
    # Find max frequency and corresponding label
    index = np.argmax(output[1])
    return output[0][index]
################################

#Init webcam
webcam = cv2.VideoCapture(0)
# Face Detection
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
skip = 0
dataset_path = './knn_openCV/'
face_data = [] 
labels = []
class_id = 0 # Labels for the given file
names = {} # Mapping btw id - name

# Data Preparation
for dataset in os.listdir(dataset_path):
    #print("Loaded "+ dataset)
    if dataset.endswith('.npy'):
        # Create a mapping btw class_id and name
        names[class_id] = dataset[:-4] # extract .npy part in filename
        data_item = np.load(dataset_path + dataset)
        face_data.append(data_item)
        # Create ;abels for the class
        target = class_id * np.ones((data_item.shape[0],))
        class_id += 1
        labels.append(target)
#print('face data', face_data)
#print('face labels', labels)
# join a sequence of arrays 
face_dataset = np.concatenate(face_data, axis=0)
face_labels = np.concatenate(labels, axis=0).reshape((-1, 1))
trainset = np.concatenate((face_dataset, face_labels), axis=1)
#print('trainset shape ', trainset.shape)

# Testing 
while True:
    ret,frame = webcam.read()
    if (ret == False):
        continue
    faces = face_cascade.detectMultiScale(frame, 1.3, 5)
    if(len(faces) == 0):
        continue
    for face in faces:
        x, y, w, h = face
        # Get the face ROI
        offset = 10
        face_section = frame[y-offset:y+h+offset, x-offset:x+w+offset]
        face_section = cv2.resize(face_section,(100,100))
        # Predicted Label 
        prediction = knn(trainset, face_section.flatten())
        #print('prediction knn ', prediction)
        # Display on the screen the name and bounding box 
        #print('names ', names)
        pred_name = names[int(prediction)]
        cv2.putText(frame, pred_name, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 0, 0), 2, cv2.LINE_AA)
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 255), 2)
    cv2.imshow("Faces",frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
            break
webcam.release()
cv2.destroyAllWindows()  